stages:
  - build
  - test
  - lint

build-frontend:
  stage: build
  image: node:16-alpine
  script:
    - cd frontend/
    - npm ci
    - npm run build

frontend-linting-tests:
  stage: lint
  retry: 2
  image: node:16-alpine
  script:
    - cd frontend/
    - npm ci
    - node_modules/eslint/bin/eslint.js .

backend_linting_tests:
  stage: lint
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip
    - pip install black click==8.0.4
  script:
    - cd backend
    - black . --check --verbose --color --extend-exclude="migrations|manage.py"

django-tests:
  stage: test
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - pip install pytest-django
  script:
    - cd backend
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: backend/report.xml

react-tests:
  stage: test
  image: node:16-alpine
  retry: 2
  script:
    - cd frontend/
    - npm ci
    - CI=true npm run test -- --testResultsProcessor=\"jest-junit\"
  artifacts:
    when: always
    reports:
      junit: frontend/junit.xml
